/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ComptrollerInterface } from "./ComptrollerInterface";
export type { ComptrollerInterfaceG1 } from "./ComptrollerInterfaceG1";
export type { ComptrollerInterfaceG2 } from "./ComptrollerInterfaceG2";
export type { IComptroller } from "./IComptroller";
export type { INAIVault } from "./INAIVault";
