/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace InterestRateModelLens {
  export type SimulationResponseStruct = {
    borrowSimulation: PromiseOrValue<BigNumberish>[];
    supplySimulation: PromiseOrValue<BigNumberish>[];
  };

  export type SimulationResponseStructOutput = [BigNumber[], BigNumber[]] & {
    borrowSimulation: BigNumber[];
    supplySimulation: BigNumber[];
  };
}

export interface InterestRateModelLensInterface extends utils.Interface {
  functions: {
    "getSimulationResponse(uint256,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getSimulationResponse"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSimulationResponse",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSimulationResponse",
    data: BytesLike
  ): Result;

  events: {};
}

export interface InterestRateModelLens extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InterestRateModelLensInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSimulationResponse(
      referenceAmountInWei: PromiseOrValue<BigNumberish>,
      interestRateModel: PromiseOrValue<string>,
      reserveFactorMantissa: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[InterestRateModelLens.SimulationResponseStructOutput]>;
  };

  getSimulationResponse(
    referenceAmountInWei: PromiseOrValue<BigNumberish>,
    interestRateModel: PromiseOrValue<string>,
    reserveFactorMantissa: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InterestRateModelLens.SimulationResponseStructOutput>;

  callStatic: {
    getSimulationResponse(
      referenceAmountInWei: PromiseOrValue<BigNumberish>,
      interestRateModel: PromiseOrValue<string>,
      reserveFactorMantissa: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InterestRateModelLens.SimulationResponseStructOutput>;
  };

  filters: {};

  estimateGas: {
    getSimulationResponse(
      referenceAmountInWei: PromiseOrValue<BigNumberish>,
      interestRateModel: PromiseOrValue<string>,
      reserveFactorMantissa: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSimulationResponse(
      referenceAmountInWei: PromiseOrValue<BigNumberish>,
      interestRateModel: PromiseOrValue<string>,
      reserveFactorMantissa: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
