/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as governorAlpha2Sol from "./GovernorAlpha2.sol";
import type * as governorAlphaSol from "./GovernorAlpha.sol";
import type * as governorBravoInterfacesSol from "./GovernorBravoInterfaces.sol";
import type * as nwlSol from "./NWL.sol";
import type * as sxpSol from "./SXP.sol";

export type { governorAlphaSol };

export type { governorAlpha2Sol };

export type { governorBravoInterfacesSol };

export type { nwlSol };

export type { sxpSol };
export type { AccessControlManager } from "./AccessControlManager";
export type { GovernorBravoDelegate } from "./GovernorBravoDelegate";
export type { GovernorBravoDelegator } from "./GovernorBravoDelegator";
