/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  NwlLike,
  NwlLikeInterface,
} from "../../../contracts/NNwlLikeDelegate.sol/NwlLike";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "delegatee",
        type: "address",
      },
    ],
    name: "delegate",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class NwlLike__factory {
  static readonly abi = _abi;
  static createInterface(): NwlLikeInterface {
    return new utils.Interface(_abi) as NwlLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NwlLike {
    return new Contract(address, _abi, signerOrProvider) as NwlLike;
  }
}
