/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  NWLInterface,
  NWLInterfaceInterface,
} from "../../../../contracts/Governance/GovernorAlpha.sol/NWLInterface";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "getPriorVotes",
    outputs: [
      {
        internalType: "uint96",
        name: "",
        type: "uint96",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class NWLInterface__factory {
  static readonly abi = _abi;
  static createInterface(): NWLInterfaceInterface {
    return new utils.Interface(_abi) as NWLInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NWLInterface {
    return new Contract(address, _abi, signerOrProvider) as NWLInterface;
  }
}
