/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as nwlVestingStorageSol from "./NWLVestingStorage.sol";
import type * as vrtConverterStorageSol from "./VRTConverterStorage.sol";

export type { nwlVestingStorageSol };

export type { vrtConverterStorageSol };
export type { INWLVesting } from "./INWLVesting";
export type { NWLVesting } from "./NWLVesting";
export type { NWLVestingProxy } from "./NWLVestingProxy";
export type { VRTConverter } from "./VRTConverter";
export type { VRTConverterProxy } from "./VRTConverterProxy";
