/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as vrtVaultStorageSol from "./VRTVaultStorage.sol";
export { VRTVault__factory } from "./VRTVault__factory";
export { VRTVaultProxy__factory } from "./VRTVaultProxy__factory";
