/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { PromiseOrValue } from "../../../common";
import type {
  NAIControllerErrorReporter,
  NAIControllerErrorReporterInterface,
} from "../../../contracts/ErrorReporter.sol/NAIControllerErrorReporter";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "error",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "info",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "detail",
        type: "uint256",
      },
    ],
    name: "Failure",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603e80601d6000396000f3fe6080604052600080fdfea265627a7a72315820720b7815c867bbc4f4f088abf38b1f58af671b9526fc25cc02f54d25b227dde664736f6c63430005100032";

type NAIControllerErrorReporterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NAIControllerErrorReporterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NAIControllerErrorReporter__factory extends ContractFactory {
  constructor(...args: NAIControllerErrorReporterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<NAIControllerErrorReporter> {
    return super.deploy(overrides || {}) as Promise<NAIControllerErrorReporter>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): NAIControllerErrorReporter {
    return super.attach(address) as NAIControllerErrorReporter;
  }
  override connect(signer: Signer): NAIControllerErrorReporter__factory {
    return super.connect(signer) as NAIControllerErrorReporter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NAIControllerErrorReporterInterface {
    return new utils.Interface(_abi) as NAIControllerErrorReporterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NAIControllerErrorReporter {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NAIControllerErrorReporter;
  }
}
