/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PriceOracleProxy__factory } from "./PriceOracleProxy__factory";
export { V1PriceOracleInterface__factory } from "./V1PriceOracleInterface__factory";
