/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBEP20 } from "./IBEP20";
export type { Owned } from "./Owned";
export type { ReentrancyGuard } from "./ReentrancyGuard";
export type { Tokenlock } from "./Tokenlock";
export type { WithAdmin } from "./WithAdmin";
